### PR TITLE
Added Borgun provider to the currency endpoint

### PR DESCRIPTION
**Pull request by jonoskar**
A different data scheme than Arion, M5 and Landsbankinn. However, Borgun API has far more currencies to offer so it's definitely a valuable provider.

Sample response:
```javascript
results: [
	{
		currencyCode: "ALL",
		currencyDescription: "lek",
		currencyRate: 1.08005,
		country: "Albanía",
		countryEnglish: "Albania",
		countryCode: "ALB",
		rateDate: "10.2.2016"
	},
	{
		currencyCode: "DZD",
		currencyDescription: "denari, alsírskur",
		currencyRate: 1.25288,
		country: "Alsír",
		countryEnglish: "Algeria",
		countryCode: "DZA",
		rateDate: "10.2.2016"
	}
]
```

### CODE REVIEW

**Comment by jonoskar** [comment]
Yeah... I have nothing to do with those failing tests :grin:

**Comment by koddsson** [comment]
LGTM

**Comment by kristjanmik** [comment]
Great job @jonoskar! Thanks for contributing :+1:  
The endpoint will not be deployed unless we fix the tests. I will take a look over the weekend.

**Comment by kristjanmik** [comment]
Me and @koddsson did some shovelling and your code is now in production at https://apis.is/currency/borgun :tada:

**Pull request merged**
