### PR TITLE
Replace eslint with xo

### PR DESCRIPTION
**Pull request by koddsson**
I was doing some exploring and found [xo](https://github.com/sindresorhus/xo) and it looks pretty neat to me. The biggest drawback seems to be that you need to add a `xo` plugin to your `$EDITOR` but if that's a big drawback I think we could just extend [`eslint-config-xo`](https://github.com/sindresorhus/eslint-config-xo).

I disabled most of the rules but left those that didn't need a lot of work and made sense to me and fixed the issues that `xo` was reporting.

### CODE REVIEW

**Comment by benediktvaldez** [comment]
Large changeset and doesn't really matter IMHO. XO is great for exactly that reason.

My vote is to fix the conflicts and merge asap

**Comment by koddsson** [comment]
@benediktvaldez What do you think about people needing to config a different flow for their editor to use `xo` over `eslint`?

**Comment by benediktvaldez** [comment]
The simplest way to solve that would be to create a `.eslintrc` file in the root with 

```
{
	"extends": "xo"
}
```

This should work in most editors that support eslint

**Comment by koddsson** [comment]
Ah lol, of course 😄

**Comment by koddsson** [comment]
I say we go for this and then we can change to the `xo-config` if we want to

**Comment by koddsson** [comment]
Nothing changed in the tests here which makes me believe that the tests might be flaky after #403  😭

**Pull request merged**
