### PR TITLE
created a scraper for hljomahollin keflavik

### PR DESCRIPTION
**Pull request by hafsteinn**

### CODE REVIEW

**Comment by koddsson** [comment]
Awesome @hafsteinn. We'll try to review this as soon as we can and get back to you. We sadly all have day jobs :disappointed: so it's probably not gonna be until some time this evening at the first. Feel free to ping us here if you start getting impatient! :)

**Comment by kristjanmik** [comment]
This looks good! I'm pulling this in. Keep up the good work @koddsson

**Comment by kristjanmik** [comment]
This looks good! I'm pulling this in. Keep up the good work @hafsteinn

**Comment by hafsteinn** [comment]
Nice! I'll try to get to the docs tonight.

**Pull request merged**
