### PR TITLE
feat: generate documentation from markdown files

### PR DESCRIPTION
**Pull request by koddsson**
Here's a PR for how I see the documentation being in the future. It seems that our documentation is kind of lost somewhere(?) and I thought I'd take a stab at making a super simple documentation framework.

1. It's easy to lint for missing documentation (is there a `documentation.md` file in the endpoint folder?)
2. Written in markdown so it's real easy to read and write (and renders well in github!)
3. The whole "framework" is currently only 14 lines + 2 npm packages.

I figured I'd open this PR to keep my work out in the open and am interested in any feedback on stuff you really feel like should be in a documentation framework for us.

### CODE REVIEW

**Comment by koddsson** [comment]
Here's how it's currently looking:

image

Obviously missing some stuff but I'm amazed at how much I was able to do with little CSS.

**Comment by kristjanmik** [comment]
This looks great! Have you thought about how we should implement this as our main doc?

**Comment by koddsson** [comment]
I was thinking about utilizing [ghpages](https://www.npmjs.com/package/gh-pages#command-line-utility) to deploy to Github Pages on each build.

**Comment by koddsson** [comment]
Things I want to do:

- [ ] Create a header
- [ ] Create the rest of the pages
- [ ] Create a footer

**Comment by koddsson** [comment]
I added all the docs that currently exists on `docs.apis.is` but there are some missing. Pretty sure I won't add them in this PR though.

I kind of want to merge this as is and make a header and footer in another PR as well as more tools to make writing docs even easier.

**Comment by MiniGod** [comment]
How flexible is this? Could it be possible to add some functionality to the docs in the future so it's not just a static page? Like doing real calls to the API to load responses. Possible to add a sidebar? I have no experience with `marked` so I'm just curious about what we can possibly turn this into in the future.

**Comment by koddsson** [comment]
@MiniGod Sure! Since apis.is is CORS enabled we can just add some javascript to fetch the resources. Since the markdown standard allows arbitrary HTML we can basically do everything we want in the docs.

**Comment by MiniGod** [comment]
Randomly stumbled upon this in the settings:

image

We can host the docs page directly from /docs on `master`, if we want?
In contrast to `gh-pages` that you linked above, we would have to commit the built html to master :-1: 
At least we have the option you know. I didn't know it was possible.

**Comment by koddsson** [comment]
Oh that's cool! Didn't know that was a option! So what `gh-pages` does is that it will build the page and then take the `dist` folder and commit that to the `gh-pages` branch. But this option looks good to me if we're cool with having the compiled HTML on the master branch.

**Comment by koddsson** [comment]
This hasn't gotten any comments in a while and since it's adding stuff and not removing anything I'm gonna move this forward and merge this after resolving the conflict.

**Comment by koddsson** [comment]
Not sure why the tests are loading the markdown files. Looking at that now.

**Comment by koddsson** [comment]
I think the currency endpoint might need test fixtures, it seems to be breaking a from day to day making me think there are some time sensitive data being saved somehow. Not sure how it would fail the tests but I'm gonna keep 👀  on it.

**Pull request merged**
