### PR TITLE
Up the timeout for a flaky /horses test

### PR DESCRIPTION
**Pull request by koddsson**
This test was failing on master randomly.

### CODE REVIEW

**Comment by koddsson** [comment]
Let's see this ship! WHOO! :shipit:

**Comment by koddsson** [comment]
@kristjanmik Does this error mean anything to you? https://codeship.com/projects/63542/builds/13533162 :sob:

**Comment by kristjanmik** [comment]
I'm on this. Advania has to fix the account for me to be able to fix this. They will probably fix it tomorrow

**Comment by koddsson** [comment]
Ah ok, awesome :) Thanks for dealing with this <3

**Comment by kristjanmik** [comment]
Done!

**Pull request merged**
