### PR TITLE
Do NOT do individual requests for multi-result data if horses not less than 8!

### PR DESCRIPTION
**Pull request by Loknar**
My assumptions in https://github.com/apis-is/apis/pull/273 that we would get like max 8 horses in multi-responses were terribly wrong!!

Check out the below link, then merge this asap, and afterwards scream if you need to.
http://www.worldfengur.com/freezone_horse.jsp?c=EN&fnr=&nafn=a&uppruni=a&ormerkja=&leitahnappur=Search+&leita=1

### CODE REVIEW

**Comment by koddsson** [comment]
Whoops. I accidentally merged without waiting for the tests D:

**Comment by koddsson** [comment]
@Loknar Can you make another PR to fix those lint issues?

**Comment by koddsson** [comment]
https://travis-ci.org/apis-is/apis/jobs/121283334#L554

**Comment by Loknar** [comment]
will do

**Pull request merged**
