### PR TITLE
Enforce no-semicolons in codebase

### PR DESCRIPTION
**Pull request by benediktvaldez**
Fundamentally disagree with #282 so I'm suggesting we revert it

http://slides.com/evanyou/semicolons
https://medium.com/@goatslacker/no-you-dont-need-semicolons-148d936b9cf2#.ycg5ulsl2

Waiting on some discussion before merging this

@koddsson @kristjanmik

### CODE REVIEW

**Comment by koddsson** [comment]
Ah sorry, I wrongly assumed it'd be all gravy.

**Comment by benediktvaldez** [comment]
To be fair I made the original decision on my own assuming the same 😉 

Do you guys have strong opinions either way?

**Comment by koddsson** [comment]
I _really_ like having semi-columns but I suspect I do because I already use them in every JS project at work. Is it cool if I think it over, read those posts and gather my thoughts about it?

In any case I don't think it's a big deal either way :P

**Comment by benediktvaldez** [comment]
Please do - let's leave this open while we consider it.. A few months ago I'd have agreed with you completely, but after reading some of theses posts and having moved to using no-semi-colons in all my JS projects both at work and personal I'm loving it more and more.. I've even stopped telling people at nodeschool to use them 😄 (although I haven't gone so far as to tell them to remove them, merely pointing out that they're optional)

**Comment by koddsson** [comment]
My only thing is that there are some caveats with not using semi colons? At least according to [this video](https://www.youtube.com/watch?v=gsfbh17Ax9I).

But I don't think it's gonna be a hassle. I say we just go for it and see what's what. :+1:

**Comment by benediktvaldez** [comment]
@koddsson This is the same video I watched, and I ended up ignoring those caveats since they are all bad practice and prevented by our lint config anyway!

So, YAY!

**Pull request merged**
