### PR TITLE
Added docs for worldfengur endpoint

### PR DESCRIPTION
**Pull request by Loknar**
Related to recently added worldfengur endpoint https://github.com/apis-is/apis/commit/9074841294d8e28bb4b9b1f7918ed64708a022d0
Created custom font-awesome icon called icelandic-horse, added font files to fonts/custom folder and created a simple css patch file

### CODE REVIEW

**Comment by koddsson** [comment]
This is awesome! I love that you added a horse icon :horse:

Do you have this running locally? Can you post a screenshot of how it looks here?

**Comment by Loknar** [comment]
http://i.imgur.com/NmaXcPH.jpg
img1
http://i.imgur.com/LuNmyQ9.jpg
img2

**Comment by koddsson** [comment]
This is amazing and I'm shipping it!

**Comment by koddsson** [comment]
@kristjanmik I've shipped the docs and the code is in the master branch. Can we ship the API so the endpoint gets added?

**Comment by kristjanmik** [comment]
@koddsson the code is automatically deployed once the tests pass

**Comment by koddsson** [comment]
Hmm I wonder if the deploy failed then because it's not live for me.

**Comment by koddsson** [comment]
I restarted the build. Let's see if it will deploy.

**Pull request merged**
