### PR TITLE
Add varnish in a fig/docker containment.

### PR DESCRIPTION
**Pull request by koddsson**
This patch started as a way to add [varnish](https://www.varnish-cache.org/) to the apis stack but adding anything to a open source stack can become kind of hard since you have no way of knowing how things are run in production.

Enter [docker](https://www.docker.com/) and [fig](http://www.fig.sh/). Docker is a great way to run applications in linux containers and fig is a really easy synchronizer for docker containers.

With this patch you only need to run `fig up` to have the full stack up and running on your local machine, auto configured and ~~ready to scale (`fig scale web=3`)~~* given you have a docker daemon and fig setup correctly. The varnish container is exposed on port 6000.

I believe this will give us a way of controlling what the technical stack from within the repository (possibly attracting people interested in devopsy stuff), a way to autoscale and possibly some security benefits (since it's running in a container).

\* Turns out this isn't true.

### CODE REVIEW

**Comment by koddsson** [comment]
If we end up wanting this we'll need to make some changes to the server.

**Comment by koddsson** [comment]
Once this is merged and running in prod (if it doesn't get shot down) I'll start working on letting the endpoints dictate how long the data they provide should live in varnish cache.

**Comment by MiniGod** [comment]
`fig` / `docker-compose` is awesome in development, and we can probably start with running that in beta, but I'm not sure if its a good fit in the long run (when we release v2) as we will probably run on multiple machines and want the ability to scale on demand. I have some ideas we can talk about later...

So, I think we can merge this if you add a `.vcl` and use it in varnish. Probably by adding something like this to `fig.yml`:
```
volumes:
- ./varnish.vcl:/etc/varnish/default.vcl
```

Also, lets rename `fig.yml` to `docker-compose.yml` as thats the new name?

**Comment by koddsson** [comment]
>if you add a .vcl

Why do we need a .vcl?

**Comment by MiniGod** [comment]
> Why do we need a .vcl?
We have to be able to configure varnish. add cors headers, customize caching, running v1 and v2 on same hostname requires some custom routing, etc...

**Comment by koddsson** [comment]
Got'cha. Although would we want to have CORS control in the application via something like the [cors module](https://www.npmjs.com/package/cors)?

Also you wanna merge this since I've added the `varnish` folder?

**Comment by MiniGod** [comment]
Why do you want the application to add the CORS headers?

Concerning performance, I think the application servers should do as little as possible. Varnish is much better at manipulating HTTP than node, so lets let it do what its good at... imo. But adding that to varnish can be done later.

---
> you wanna merge this

I get an error when running `docker-compose up`. Looks like you forgot to install the npm dependencies in the build?

**Comment by koddsson** [comment]
>Why do you want the application to add the CORS headers?

I've never used varnish before so I don't know how it works but I was thinking something along the lines of being able to finely tune which routes should attach a CORS header and which ones shouldn't but maybe we won't need that or it's possible in varnish.

>I get an error

Wanna post it so I can try to reproduce?

**Comment by MiniGod** [comment]
```
git clone git://github.com/kristjanmik/apis.git
cd apis
git checkout origin/v2-varnish
docker-compose build
docker-compose up
```

Output from `docker-compose up`
```
Recreating apis_web_1...
Recreating apis_varnish_1...
Attaching to apis_web_1, apis_varnish_1
web_1     |
web_1     | > v2apis@2.0.0 start /app
web_1     | > node index.js
web_1     |
web_1     | module.js:338
web_1     |     throw err;
web_1     |           ^
web_1     | Error: Cannot find module 'express'
web_1     |     at Function.Module._resolveFilename (module.js:336:15)
web_1     |     at Function.Module._load (module.js:278:25)
web_1     |     at Module.require (module.js:365:17)
web_1     |     at require (module.js:384:17)
...
```
and so on

**Comment by koddsson** [comment]
@MiniGod ping.

**Comment by MiniGod** [comment]
It should be part of the build step, i.e. better to have `npm install` in `Dockerfile`. Only need to do it once, not every time you start it. `npm start` isn't only used by docker-compose.

**Comment by MiniGod** [comment]
We should write the vcl before merging this. Doesn't make much sense at the moment. I will look into it (but no promises. you you can too if you want, heh).

**Comment by koddsson** [comment]
Sure! What should this vcl accomplish? I've just checked the defaults and didn't know what more to add.

**Comment by MiniGod** [comment]
Some ideas (ordered by priority):

1. There should be no way to force fresh data, even if  the `cookie` header is present.
2. Increase the default ttl to 60 minutes, or even 24 hours. (default ttl = 2m)
3. Add headers whether its a cache hit or miss (`X-Cache: HIT`)
4. Redirect `/` to docs.beta.apis.is

**Comment by kristjanmik** [comment]
what about force fresh via headers, are we not going to support that?

**Comment by MiniGod** [comment]
You can always add a random query parameter...?

**Comment by MiniGod** [comment]
i was mostly thinking that the `cookie` header shouldn't invalidate, because  if we run some analytics on `docs.apis.is`, it might set cookies on `.apis.is` and your browser will always get fresh data even if you dont want it, and that will be slooooww

**Comment by MiniGod** [comment]
I forgot to [add CORS to the list.](https://github.com/apis-is/apis/pull/192#issuecomment-77135663)

> 2 . Add CORS headers

**Comment by kristjanmik** [comment]
@MiniGod @koddsson What is the status on this one?

**Pull request closed without merging**
