### PR TITLE
chore(test): mock all request responses

### PR DESCRIPTION
**Pull request by koddsson**
This patch adds mocked responses to all the requests made in the tests.

Here's how I generated the data in `mock-data.json` using [nock]:

```diff
diff --git a/test/integration/endpoints.js b/test/integration/endpoints.js
index 4ab166c..604de5e 100644
--- a/test/integration/endpoints.js
+++ b/test/integration/endpoints.js
@@ -4,10 +4,28 @@ process.env.INTEGRATION = true
 import fs from 'fs'
 import path from 'path'
 import fileModule from 'file'
+import nock from 'nock'
 
 const testDir = 'tests'
 const testFileName = 'integration_test.js'
 
+before(() => {
+  nock.recorder.rec({
+    output_objects: true,
+    dont_print: true,
+  })
+})
+
+after((done) => {
+  const nockCallObjects = nock.recorder.play()
+  fs.writeFile('./mock-data.json', JSON.stringify(nockCallObjects), (error) => {
+    if (error) {
+      console.error(error)
+    }
+    done()
+  })
+})
+
 describe('endpoint', () => {
   it('should load the server and set everything up properly', (done) => {
     const app = require(`${process.cwd()}/server`)
```

This means that our tests don't make any requests which has been a problem in the past. This enables us to mock future endpoints from the beginning and maybe we can start moving the mocked data into the tests and delete the json file in the future.

[nock]: https://github.com/node-nock/nock#recording

### CODE REVIEW

**Comment by koddsson** [comment]
This failure actually makes sense since the weather API test is failing on `master` as well 😆

**Comment by koddsson** [comment]
It looks like the weather site is just broken right now so the failure makes sense at this point of time

image

But this is the kind of issues we get rid of by mocking the website responses like I'm doing in this PR. The fact that this PR and master is blocked on something that we can't change is pretty bad.

**Comment by koddsson** [comment]
Regenerated the mock json data in a more human readable form so that diffs will be better in the future.

**Comment by koddsson** [comment]
The CI build is running in ~30sec with linting and testing running in ~5sec each.

image

**Comment by koddsson** [comment]
@MiniGod How's this?

**Comment by koddsson** [comment]
I don't wanna tout my own horn but it's been really fun working in this PR with the really fast and consistent tests 🙏

**Comment by kristjanmik** [comment]
This is AMAZING! You are not tooting your horn at all, we will have to call Gudni, the pineapple president to give you one of his fálkaorðas

**Comment by MiniGod** [comment]
Great note about how to do the mock data for new endpoints. LGTM now.

I love this PR so much. I and @kristjanmik were talking about apis.is last weekend, and how much it sucks that the tests fail if the sources are not up, and hence the automatic deploy fails too. This is seriously such an amazing PR! Kudos to @koddsson

all my thumbs are up

**Pull request merged**
